version: "3"
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSION=5
      - SE_NODE_CONCURRENT_REQUESTS=5
    networks:
      - selenium-grid

  chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-node-chrome
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_PORT=5555
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid

  firefox:
    image: selenium/node-firefox:latest
    container_name: selenium-node-firefox
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_PORT=5555
    volumes:
      - /dev/shm:/dev/shm
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge
